language: go
go:
  - 1.15.2

before_install:
  - go get -v golang.org/x/tools/cmd/cover
  - go get -v github.com/axw/gocov/gocov
  - go get -u golang.org/x/lint/golint

install:
  - go install -race -v std
  - go get -race -t -v ./...
  - go install -race -v ./...

script:
  - "$HOME/gopath/bin/golint ."
  - go test -timeout 1s -cpu=2 -race -v ./...
  - go test -timeout 1s -cpu=2 -covermode=atomic ./...
